# add the linters you want stickler to use for this project
linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './.eslintrc.json'
    fixer: true

# add the files here you want to be ignored by stylelint

files:
  ignore:
      - 'bundle/*'
      - 'src/js/phaser.min.js'
      - 'webpack/base.js'
      - '"webpack/prod.js'

# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config

# find full documentation here: https://stickler-ci.com/docs